# Generated by Django 5.2.6 on 2025-11-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="saldo",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="Saldo"
            ),
        ),
    ]
