# Generated by Django 5.2.6 on 2025-12-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_cliente_saldo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="veiculo",
            name="foto_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
