# Generated by Django 5.2.6 on 2025-12-06 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_veiculo_foto_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cliente",
            old_name="endereco",
            new_name="rua",
        ),
    ]
